# Generated by Django 4.2.3 on 2023-07-12 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosmedicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesionales',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profesionales',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunes', models.BooleanField()),
                ('martes', models.BooleanField()),
                ('miercoles', models.BooleanField()),
                ('jueves', models.BooleanField()),
                ('viernes', models.BooleanField()),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviciosmedicos.profesionales')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviciosmedicos.servicios')),
            ],
        ),
    ]
