# Generated by Django 4.2.3 on 2023-07-12 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosmedicos', '0002_alter_profesionales_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atencion',
            options={'verbose_name': 'atencion', 'verbose_name_plural': 'atenciones'},
        ),
        migrations.AlterModelOptions(
            name='profesionales',
            options={'verbose_name': 'profesional', 'verbose_name_plural': 'profesionales'},
        ),
        migrations.AlterModelOptions(
            name='servicios',
            options={'verbose_name': 'servicio', 'verbose_name_plural': 'servicios'},
        ),
    ]
